.TH "Camiao" 3 "Sun May 28 2023" "21089_Projeto_EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Camiao \- Estrutura de \fBCamiao\fP Que Recolhe Meios de Mobilidade\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Localizacao\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBidOrigem\fP"
.br
.ti -1c
.RI "float \fBcargaAtual\fP"
.br
.ti -1c
.RI "float \fBcargaMaxima\fP"
.br
.ti -1c
.RI "struct \fBLocalizacaoPostos\fP * \fBlocalizacaoAtual\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura de \fBCamiao\fP Que Recolhe Meios de Mobilidade\&. 

Um \fBCamiao\fP contém um idOrigem (@idOrigem), cargaAtual (@cargaAtual) , cargaMaxima (@cargaMaxima) e localizacaoAtual (@localizacaoAtual)\&. 
.SH "Member Data Documentation"
.PP 
.SS "float Camiao::cargaAtual"

.SS "float Camiao::cargaMaxima"

.SS "int Camiao::idOrigem"

.SS "struct \fBLocalizacaoPostos\fP* Camiao::localizacaoAtual"


.SH "Author"
.PP 
Generated automatically by Doxygen for 21089_Projeto_EDA from the source code\&.
