.TH "CaminhoCamiao" 3 "Sun May 28 2023" "21089_Projeto_EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CaminhoCamiao \- Estrutura Para Guardar os Pontos Que o \fBCamiao\fP irá Prosseguir\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Localizacao\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBidPosto\fP"
.br
.ti -1c
.RI "int \fBidMeio\fP"
.br
.ti -1c
.RI "int \fBpesoMeio\fP"
.br
.ti -1c
.RI "struct \fBCaminhoCamiao\fP * \fBproximo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura Para Guardar os Pontos Que o \fBCamiao\fP irá Prosseguir\&. 

Um \fBCaminhoCamiao\fP contém um idPosto (@idPosto), idMeio (@idMeio) e pesoMeio (@pesoMeio)\&. Contém apontador para próximo \fBCaminhoCamiao\fP 
.SH "Member Data Documentation"
.PP 
.SS "int CaminhoCamiao::idMeio"

.SS "int CaminhoCamiao::idPosto"

.SS "int CaminhoCamiao::pesoMeio"

.SS "struct \fBCaminhoCamiao\fP* CaminhoCamiao::proximo"


.SH "Author"
.PP 
Generated automatically by Doxygen for 21089_Projeto_EDA from the source code\&.
