.TH "LocalizacaoPostos" 3 "Sun May 28 2023" "21089_Projeto_EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LocalizacaoPostos \- Estrutura para Grafo orientado de \fBPostos\fP de Localizacao\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Localizacao\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBPostos\fP * \fBposto\fP"
.br
.ti -1c
.RI "struct \fBLocalizacaoPostos\fP * \fBproximo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura para Grafo orientado de \fBPostos\fP de Localizacao\&. 

Um \fBLocalizacaoPostos\fP contém posto (@posto)\&. Contém apontador para próximo \fBLocalizacaoPostos\fP 
.SH "Member Data Documentation"
.PP 
.SS "struct \fBPostos\fP* LocalizacaoPostos::posto"

.SS "struct \fBLocalizacaoPostos\fP* LocalizacaoPostos::proximo"


.SH "Author"
.PP 
Generated automatically by Doxygen for 21089_Projeto_EDA from the source code\&.
