.TH "MeiosDeMobilidade" 3 "Sun May 28 2023" "21089_Projeto_EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MeiosDeMobilidade
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MeioDeMobilidade\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "char \fBtipo\fP [\fBLARGURAGERALSTRING\fP]"
.br
.ti -1c
.RI "int \fBcargaBateria\fP"
.br
.ti -1c
.RI "float \fBcusto\fP"
.br
.ti -1c
.RI "float \fBpeso\fP"
.br
.ti -1c
.RI "char \fBcidade\fP [\fBLARGURAGERALSTRING\fP]"
.br
.ti -1c
.RI "float \fBlatitude\fP"
.br
.ti -1c
.RI "float \fBlongitude\fP"
.br
.ti -1c
.RI "bool \fBestado\fP"
.br
.ti -1c
.RI "struct \fBAluguer\fP * \fBaluguer\fP"
.br
.ti -1c
.RI "struct \fBMeiosDeMobilidade\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBAluguer\fP* MeiosDeMobilidade::aluguer"

.SS "int MeiosDeMobilidade::cargaBateria"

.SS "char MeiosDeMobilidade::cidade[\fBLARGURAGERALSTRING\fP]"

.SS "float MeiosDeMobilidade::custo"

.SS "bool MeiosDeMobilidade::estado"

.SS "int MeiosDeMobilidade::id"

.SS "float MeiosDeMobilidade::latitude"

.SS "float MeiosDeMobilidade::longitude"

.SS "struct \fBMeiosDeMobilidade\fP* MeiosDeMobilidade::next"

.SS "float MeiosDeMobilidade::peso"

.SS "char MeiosDeMobilidade::tipo[\fBLARGURAGERALSTRING\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for 21089_Projeto_EDA from the source code\&.
