.TH "Postos" 3 "Sun May 28 2023" "21089_Projeto_EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Postos \- Estrutura de Vertices (\fBPostos\fP) para grafo orientado de \fBPostos\fP de Localizacao (\fBLocalizacaoPostos\fP)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Localizacao\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "char \fBcidade\fP [\fBLARGURAGERALSTRING\fP]"
.br
.ti -1c
.RI "float \fBlatitude\fP"
.br
.ti -1c
.RI "float \fBlongitude\fP"
.br
.ti -1c
.RI "bool \fBvisitado\fP"
.br
.ti -1c
.RI "struct \fBLocalizacaoPostosAdjacentes\fP * \fBpostosAdjacentes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura de Vertices (\fBPostos\fP) para grafo orientado de \fBPostos\fP de Localizacao (\fBLocalizacaoPostos\fP) 

Um \fBPostos\fP contém um id (@id), cidade (@cidade) ,latitude (@latitude) , longitude (@longitude), visitado (@visitado) e postosAdjacentes (@postosAdjacentes)\&. 
.SH "Member Data Documentation"
.PP 
.SS "char Postos::cidade[\fBLARGURAGERALSTRING\fP]"

.SS "int Postos::id"

.SS "float Postos::latitude"

.SS "float Postos::longitude"

.SS "struct \fBLocalizacaoPostosAdjacentes\fP* Postos::postosAdjacentes"

.SS "bool Postos::visitado"


.SH "Author"
.PP 
Generated automatically by Doxygen for 21089_Projeto_EDA from the source code\&.
