.TH "MeiosDeMobilidade" 3 "Sat Mar 18 2023" "21089_Projeto_EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MeiosDeMobilidade \- Estrutura para armazenar Meios De Mobilidade\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MeioDeMobilidade\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "char \fBtipo\fP [50]"
.br
.ti -1c
.RI "int \fBcargaBateria\fP"
.br
.ti -1c
.RI "float \fBcusto\fP"
.br
.ti -1c
.RI "char \fBlocalizacao\fP [50]"
.br
.ti -1c
.RI "struct \fBAluguer\fP * \fBaluguer\fP"
.br
.ti -1c
.RI "struct \fBMeiosDeMobilidade\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura para armazenar Meios De Mobilidade\&. 

Um Meios De Mobilidade contém um id (@id), tipo (@tipo) ,carga da Bateria (@cargaBateria) , custo (@custo) e localizacao (@aluguer)\&. Contém apontador para próximo \fBMeiosDeMobilidade\fP 
.SH "Member Data Documentation"
.PP 
.SS "struct \fBAluguer\fP* MeiosDeMobilidade::aluguer"

.SS "int MeiosDeMobilidade::cargaBateria"

.SS "float MeiosDeMobilidade::custo"

.SS "int MeiosDeMobilidade::id"

.SS "char MeiosDeMobilidade::localizacao[50]"

.SS "struct \fBMeiosDeMobilidade\fP* MeiosDeMobilidade::next"

.SS "char MeiosDeMobilidade::tipo[50]"


.SH "Author"
.PP 
Generated automatically by Doxygen for 21089_Projeto_EDA from the source code\&.
