.TH "Source.c" 3 "Sat Mar 18 2023" "21089_Projeto_EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source.c \- Main da Aplicacao\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include 'Gestor\&.h'\fP
.br
\fC#include 'Cliente\&.h'\fP
.br
\fC#include 'MeioDeMobilidade\&.h'\fP
.br
\fC#include 'Aluguer\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_CRT_SECURE_NO_WARNINGS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main da Aplicacao\&. 


.PP
\fBAuthor\fP
.RS 4
Rafael Silva @email a21089@alunos.ipca.pt 
.RE
.PP
\fBDate\fP
.RS 4
2023 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define _CRT_SECURE_NO_WARNINGS"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for 21089_Projeto_EDA from the source code\&.
